routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('expense','ExpenseController');
Route::post('/edit/{id}','ExpenseController@update');
Route::get('/expense/delete/{id}','ExpenseController@destroy');

Route::get('/recordSearch/{query?}','ExpenseController@expenseJson');

 

app/Expense.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Expense extends Model
{
    protected $fillable = ['date','categories','type','amount'] ;
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ExpenseController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Pagination\Paginator;
use App\Expense;
use Validator;



class ExpenseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('index'); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validation rules Starts here -->
        $rules =array(
            'date'=>'required',
            'categories'=>'required',
            'type' => 'required',
            'amount' => 'required',
        );


        $validator = Validator::make($request->all(), $rules);
            //Check to see if validation fails or passes
        if($validator->fails())
        {
            // Alert::error('Error','Somthing went wrong.. Please check errors..! ');
            return redirect()->back()->withErrors($validator)->withInput();
        }  

        $crud = new Expense();
        $crud->date = $request->date;
        $crud->categories = $request->categories;
        $crud->type = $request->type;
        $crud->amount = $request->amount;

        $crud->save();
        return redirect('/expense')->with('success','User with Image has been added..!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        // $all = Expense::paginate(5);
        return view('details');
    }
    public function expenseJson(Request $request,$query=null)
    {   
        if(!empty($query)){
        $all = Expense::where('date','like','%'.$query.'%')->get();            
        }else{
        $all = Expense::all();          
        }
        return response()->json([
           'status'=>'success',
           'message'=>'all records',
           'list'=>$all,
         ]);
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Expense::find($id);
        return view('edit',compact('data','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Expense::findOrFail($id);
        $data->date = $request->date;
        $data->categories = $request->categories;
        $data->type = $request->type;
        $data->amount = $request->amount;

        $data->save();
        return redirect('/expense/show');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $crud = Expense::findOrFail($id);
        $crud->delete();
        return redirect()->back();
    }

    
}

resources/views/details.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Expense Tracking Web App</title>

	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

	<!-- jQuery library -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<link href="{{ asset('/css/bootstrap-datetimepicker.css') }}" rel="stylesheet">

</head>
<body>
	<div class="Container ">
		<div class="col-md-12 justify-content-center">
		<div class="col-md-10" style="margin-left: 80px;" >
			<h2 style="text-align: center;">Record Details</h2>
			<br/><br/>
			<div class="row">
				  <div class="form-group">
                       		<div class="col-md-6">
                            <div class='input-group date' id='datetimepicker1'>
                                  <input type='text' class="form-control" name="date" placeholder="Select Date" autofocus required id="datesearch">
                                  <span class="input-group-addon">
                                       <span class="glyphicon glyphicon-calendar"></span>
                                  </span>
                          </div>
                      </div>
				<button class="btn btn-success" id="searchBtn">Search</button>

				<button class="btn btn-primary" id="reset">Reset</button>

				</div>
			</div><br/>
			
			<div class="table-responsive">
	
			<table class="table table-bordered table-striped" style="text-align: center;" >
				<tr>
					<th style="text-align: center;">Date </th>
					<th style="text-align: center;">Categories </th>
					<th style="text-align: center;">Type </th>
					<th style="text-align: center;">Amount</th>
					<th style="text-align: center;">Action</th>
				</tr>
				<tbody id="tBody">
					
				</tbody>
					
			</table>
			</div>
		</div>
		</div>
	</div>
	<script type="text/javascript">
		$(document).ready(function(){
			url="/recordSearch";
			search(url);
		})

		$("#reset").click(function(){
			 $("#datesearch").val("");
			 var url="/recordSearch";
			 search(url);			 
			})

		$("#searchBtn").click(function(){
			 var query=$("#datesearch").val();
			 var url="/recordSearch/"+query;
			 search(url);			 
			})

		function search(url){
			$.ajax({
			   	url:url,
			   	method:'GET',
			   	dataType:'json',
			   	success:function(data)
			   	{
                    $('#tBody').html("");
			   		var trHTML = '';
                        $.each(data.list, function (i, resp) {
                                trHTML +=
                                    '<tr><td>'
                                    + resp.date
                                    + '</td><td>'
                                    + resp.categories
                                    + '</td><td>'
                                    + resp.type
                                    + '</td><td>'
                                    + resp.amount 
                                    + '</td><td>'
                                    + '<a href="/expense/'+resp.id+'/edit" class="btn btn-primary">Edit</a>'
                                    + '<a href="/expense/delete/'+resp.id+' " class="btn btn-danger">Delete</a>'
                                    + '</td></tr>';
                        });
                        $('#tBody').append(trHTML);
		  		}
		  	})}
	</script>
	<script src="{{ asset('js/moment.js') }}"></script>
  	  <script src="{{ asset('js/bootstrap-datetimepicker.js') }}"></script>
	<script>
	$(document).ready(function () {
  	var m = moment(new Date());
  	$('#datetimepicker1').datetimepicker({
  		format: 'DD-MM-YYYY',
	 });
  });
</script>
</body>
</html>

resources/views/edit.blade.php
<!DOCTYPE html>
<html>
<head>
	<title> Expense Tracking Web App </title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

	<!-- jQuery library -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<link href="{{ asset('/css/bootstrap-datetimepicker.css') }}" rel="stylesheet">
</head>
<body>
	<div class="container" >
		<div class=" row col-md-8">
		
		<form action="/edit/{{ $data->id }}" method="POST" >
			@csrf
			<h2>Edit Expense</h2>
			<div class="form-group">

				<label>Date:</label>
                            <div class='input-group date' id='datetimepicker1'>
                                  <input type='text' class="form-control" name="date" 
                                  value="{{$data->date}}" placeholder="Select Date" autofocus required>
                                  <span class="input-group-addon">
                                       <span class="glyphicon glyphicon-calendar"></span>
                                  </span>
                          </div>
			</div><br/>
			<div class="form-group">
				<label>Categories :</label>
				<input type="text" name="categories" class="form-control" value="{{$data->categories}}" required autofocus>
			</div><br/>
			<div class="form-group">
				<label>Type :</label>
				<input type="text" name="type" class="form-control" value="{{$data->type}}" required autofocus>
			</div><br/>
			<div class="form-group">
				<label>Amount :</label>
				<input type="text" name="amount" class="form-control" value="{{$data->amount}}" required autofocus>
			</div><br/>
			<button type="submit" class="btn btn-primary">Update</button>
		</form>
		</div>
	</div>
	  <script src="{{ asset('js/moment.js') }}"></script>
  	  <script src="{{ asset('js/bootstrap-datetimepicker.js') }}"></script>
	<script>
		$(document).ready(function () {
		  var m = moment(new Date());
		  $('#datetimepicker1').datetimepicker({
		  		format: 'DD-MM-YYYY',
			 });
		  });
	</script>
</body>
</html>

resources/views/index.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Expense Tracking Web App</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

	<!-- jQuery library -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<link href="{{ asset('/css/bootstrap-datetimepicker.css') }}" rel="stylesheet">
</head>
<body>
	<div class="container" >
		<div class="row col-md-6" style="left: 200px; margin: 25px 50px 75px 100px; border-spacing: 5px; border: 1px solid black;">
		<form id="form" action="{{route('expense.store')}}" method="post" >
			@csrf
			<h2 style="text-align: center;">Expense Track App</h2>

			<div class="form-group">
                       	<label>Date:</label>
                            <div class='input-group date' id='datetimepicker1'>
                                  <input type='text' class="form-control" name="date" placeholder="Select Date" autofocus required>
                                  <span class="input-group-addon">
                                       <span class="glyphicon glyphicon-calendar"></span>
                                  </span>
                          </div>
			</div><br/>
			<div class="form-group">
				<label>Categories : </label>
				<select name="categories" class="form-control" required>
					<option value="">  </option>
					<option value="SAVINGS"> SAVINGS </option>
					<option value="CURRENT"> CURRENT </option>
					<option value="JOINT"> JOINT </option>
				</select>
			</div><br/>
			<div class="form-group">
				<label>Type : </label>
				<input type="radio" name="type" value="cash"> Cash &nbsp
				<input type="radio" name="type" value="credit"> Credit
			</div><br/>
			<div class="form-group">
				<label>Amount : </label>
				<input type="text" name="amount" class="form-control" required>
			</div>
			<div class="form-group" >
				<input type="submit"  class="btn btn-primary" > 
				<a href="/expense/show" target="_blank" class="btn btn-primary" style="float: right;"> Details </a>  
			</div>
		</form>
	</div>
	</div>
	  <script src="{{ asset('js/moment.js') }}"></script>
  	  <script src="{{ asset('js/bootstrap-datetimepicker.js') }}"></script>
	<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-
    methods.min.js"></script>
	<script>
	    $(document).ready(function () {
		    $('#form').validate({ // initialize the plugin
		        rules: {
		            date: {
		                required: true
		            },
		            categories: {
		                required: true
		            },
		            type: {
		                required: true
		            },
		            amount: {
		                required: true,
		                number: true
		            },
		        }
	    	});
		});
	</script>
<script>
$(document).ready(function () {
  var m = moment(new Date());
  $('#datetimepicker1').datetimepicker({
  		format: 'DD-MM-YYYY',
	 });
  });
</script>
</body>
</html>